---
kind: pipeline
type: docker
name: default

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: rebuild-cache
    image: zoickx/drone-helper
    commands:
      - drone-helper cache --deps="Dockerfile helix.opam"
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: build-vellvm
    image: cache--${DRONE_REPO}:${DRONE_COMMIT_AFTER}
    pull: never
    commands:
      - opam exec -- make -j 1 vellvm

  - name: compile-helix
    image: cache--${DRONE_REPO}:${DRONE_COMMIT_AFTER}
    pull: never
    commands:
      - opam exec -- make

  - name: test-helix
    image: cache--${DRONE_REPO}:${DRONE_COMMIT_AFTER}
    pull: never
    commands:
      - opam exec -- make test

  - name: notify
    image: zoickx/drone-helper
    commands:
      - drone-helper notify --discord
    when:
      status:
        - success
        - failure
    settings:
      discord_webhook_token:
        from_secret: discord_webhook_token 
      discord_webhook_id:
        from_secret: discord_webhook_id
