
This development reflects authors' Coq learning journey and contains a
lot of inelegant and redundant code. Additionally, it includes some
workarounds for bugs and limitations for older Coq versions (starting
from 8.4).

It is overdue for serious refactoring and cleanup. Amongst other things:

* Refactoring
** Some other cleanup opportunities are marked with "TODO" comments
** Rename =eT= and =eUnion= to =Embed= and =Pick=
** Rename =Diamond= to =MR=
** Many usused definitions could be removed. (Hint: try `make print-unused`)
** It looks like =Apply_Family= never used directly. Just =Apply_Family'=.
   We probably need just one definition.
** Rename implementations named =foo'= into =foo_Impl= in /SigmaHCOLImpl.v/.
  For example =eT'= should become =eT_impl=
** Run =coq-min-imports= on all codebase
** GEP definition in Coq

* Proof mechanics
** Review =_arg_proper= vs =_proper= instances
** Proof-irrelevance assumption could be avoided
* Unfinished
** Automate /DynWin/ rewriting proof
** Automate SPIRAL log reading for sequence of rewrites
   Perhaps using TemplateCoq?
** =maxnum=  implementation
   Currently implemented as C =max= macro. Should be more
   like =fmax= https://en.cppreference.com/w/c/numeric/math/fmax
   LLVM ref: https://llvm.org/docs/LangRef.html#llvm-maxnum-intrinsic
* Ideas
  - See if =coq-equations= package could be used to represent index
    functions and function arguments of =BinOp=, =Pointwise=, etc.

